server.port=8080

# ===== ROTA SALES =====
spring.cloud.gateway.server.webflux.routes[0].id=sales-route
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:4000
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/sales, /sales/**

# ===== ROTA EVENTS =====
spring.cloud.gateway.server.webflux.routes[1].id=events-route
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:4000
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/events, /events/**

# ===== CORS =====
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.corsConfigurations.[/**].allowedHeaders=*